# Generated by Django 3.2.3 on 2021-12-01 06:06

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20210820_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50, primary_key='True', serialize=False)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
