# Generated by Django 3.2.3 on 2021-12-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_auto_20211201_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(max_length=50, primary_key='True', serialize=False),
        ),
    ]
