# Generated by Django 3.2.3 on 2021-12-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_alter_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
